name = "pondyretreats"
main = "src/index.js"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

# Bind your KV namespaces
[[kv_namespaces]]
binding = "USERS_KV"
id = "e3fe3d9065cd4056b586d06cb5392746" # Replace with your actual KV namespace ID

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "19b0fd221d1b48a1a2c374beaf47cc14" # Replace with your actual KV namespace ID
